version: "3.9"

services:
  esphome:
    image: esphome/esphome
    container_name: esphome
    user: "1000:1000"   # твой UID:GID
    environment:
      - HOME=/config
      - PLATFORMIO_CORE_DIR=/config/.platformio
      - ESPHOME_DASHBOARD_USE_PING=false
    volumes:
      - ./config:/config
    ports:
      - "6052:6052"
    restart: unless-stopped

